### ISSUE TITLE
Plugin doesn't show in Octoprint Plugin manager 

### ISSUE THREAD

**Issue by asapir** [PrusaOwners/OctoPrint-PrusaMeshMap#30]
Cannot find this plugin with octoprint Plugin manager and octoprint plugin site.

thanks.

**Comment by VileBrigandier** [comment]
Hi @asapir,

This is actually intentional. Due to the plugin requiring matplotlib and numpy wheels to be compiled at install on some platforms (namely, Pi) and a majority of users running on that platform, we don't want to field the support from one off users having problems. Keeping it available on Github in this fashion makes it much more likely they'll read the documentation for Pi setup, and any updates to the release will show a notification in your Octoprint interface.

Thanks!
